# Dataset configuration
dataset:
  samples: 100000
  psf_sigma: 0.25
  exp: "superbit"
  nse_sd: 12.719674
  seed: 42
  stamp_size: 53
  pixel_size: 0.141

# Model configuration  
model:
  process_psf: true
  type: "fork-like"  # Options: mlp, cnn, resnet, forklens_psf, 
               #          research_backed, and fork-like
  galaxy:
    type: "research_backed"
  psf:
    type: "forklens_psf"
  
# Training configuration
training:
  epochs: 300
  batch_size: 128
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  patience: 25
  val_split: 0.2
  eval_interval: 1
  
# Evaluation configuration
evaluation:
  test_samples: 50000
  seed: 58
  
# Output configuration
output:
  save_path: "/home/adfield/ShearNet/model_checkpoint/unit_test/"  # Will use SHEARNET_DATA_PATH/model_checkpoint if null
  plot_path: "/home/adfield/ShearNet/plots/unit_test/"  # Will use SHEARNET_DATA_PATH/plots if null
  model_name: "FIRST_const_sigma+flux_nse_sd_12_type_exp"
  
# Plotting configuration
plotting:
  plot: true  # Whether to plot learning curves
  
# Comparison methods
comparison:
  mcal: true
  ngmix: true
  psf_model: "gauss"